### ISSUE TITLE
The compiler-plugin shouldn't override toString if it has already overridden in the parent class

### ISSUE THREAD

**Issue by semkagtn** [polyvariant/better-tostring#83] opened 2021-10-08 13:26 UTC
The first problem is compilation error. An example:
```scala
object Main extends App {
  abstract class C {
    override val toString: String = ""
  }
  case class O() extends C
}
// scalac: stable, immutable value required to override:
// override val toString: String (defined in class C)
```

The second problem is unobvious behaviour:
```scala
sealed abstract class Abstract(value: String) {
  override def toString: String = value
}

case class Cls(value: String) extends Abstract(value)

object Main extends App {
  assert(Cls("test").toString == "test") // fail
}
```

better-tostring version: 0.3.9
scala version: 2.13.4

**Comment by kubukoz** [comment] 2021-11-01 18:57
I think this is a duplicate of #34.

**Closed by kubukoz** 2021-11-01 18:57 UTC
